const diy = [
{
    diyId: 1,
    diyName: 'Scented candle',
    diyPrice: '345.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: 'A fragrant candle infused with essential oils or aromatic ingredients, designed to create a pleasant and relaxing atmosphere when lit.',
    diyImage: require('../shared/diy/candle.jpg'),
    type:'diy',
    categoryId: 3,
},
{
    diyId: 2,
    diyName: 'Scented Soap',
    diyPrice: '225.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: 'A bar of soap enriched with aromatic fragrances and essential oils, offering a luxurious and aromatic cleansing experience.',
    diyImage: require('../shared/diy/soap.jpg'),
    type:'diy',
    categoryId: 3,
},
{
    diyId: 4,
    diyName: 'Coloring Totebag',
    diyPrice: '275.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: 'A creative and customizable tote bag featuring outline designs, perfect for coloring with fabric markers or paints to create a personalized accessory.',
    diyImage: require('../shared/diy/totebag.jpg'),
    type:'diy',
},
{
    diyId: 5,
    diyName: 'Coloring Canvas',
    diyPrice: '275.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: 'A blank canvas with pre-drawn outlines, ideal for coloring with paints or markers, allowing for a fun and artistic activity to create unique artwork.',
    diyImage: require('../shared/diy/canvas.jpg'),
    type:'diy',
    categoryId: 3,
},
{
    diyId: 6,
    diyName: 'Coloring Plasters',
    diyPrice: '185.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: 'Adhesive bandages with outlined designs that can be colored in with markers or paints, making wound care more fun and personalized.',
    diyImage: require('../shared/diy/plaster.jpg'),
    type:'diy',
    categoryId: 3,
},
{
    diyId: 7,
    diyName: 'Scented Love',
    diyPrice: '495.000VND',
    diyLocation: "Available in Beanthere I - Ho Hao Hon Street and Beanthere II - Hoang Sa Street.",
    diyDescription: ' A thoughtfully curated set featuring a scented candle, a bar of scented soap, and a heartfelt love letter. The aromatic candle and soap provide a relaxing and luxurious experience, while the love letter adds a personal and romantic touch, making this gift perfect for showing affection and care.',
    diyImage: require('../shared/diy/set.jpg'),
    type:'diy',
    categoryId: 3,
},

];
export default diy;