const drinkdetails = [
    {
      drinkId: 1,
      cafeName: "Beanthere Cafe",
      image: require("../shared/drink/beancafe.jpg"),
      price: "65.000VND",
      description: "A rich and smooth coffee drink, made with a generous amount of cream or milk to achieve a velvety texture and mellow flavor. Iced only.",
      categoryId: 2,
      coffeeId: 1,
      rating: 4.8,
      included: "Double shot of espresso, creamy milk, white milk and condensed milk. Serving in bottle 200ml.",
    },
    {
      drinkId: 2,
      cafeName: "Espresso with Coconut foam",
      image: require("../shared/drink/coconutfoam.jpg"),
      price: "65.000VND",
      description: "A bold and tropical twist on traditional espresso, topped with a layer of frothy coconut foam for a blend of strong coffee and subtle coconut flavor. Iced only.",
      categoryId: 2,
      coffeeId: 1,
      rating: 4.5,
      included: "Single shot of coffee, coconut foam with coconut water.",
    },
    {
      drinkId: 3,
      cafeName: "Coconut with Matcha foam",
      image: require("../shared/drink/matchafoam.jpg"),
      price: "65.000VND",
      description: "A refreshing and exotic drink, featuring a layer of light and airy matcha foam on top of a base made from creamy coconut milk. Iced only.",
      categoryId: 2,
      coffeeId: 1,
      rating: 4.5,
      included: "Coconut water with coconut matcha foam.",
    },
    {
      drinkId: 4,
      cafeName: "Rice milk with Pandan tofu",
      image: require("../shared/drink/pandantofu.jpg"),
      price: "65.000VND",
      description: "A unique and fragrant beverage, combining the subtle sweetness of rice milk with the aromatic and soft texture of pandan-infused tofu. Be able to: Hot or Ice.",
      categoryId: 2,
      coffeeId: 1,
      rating: 4.5,
      included: "Rice milk with topping pandan tofu.",
    },
    {
      drinkId: 5,
      cafeName: "Black Coffee",
      image: require("../shared/drink/black.jpg"),
      price: "50.000VND",
      description: "Simple and pure, made from ground coffee beans brewed with hot water, without any additives like milk, sugar, or flavors. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.5,
      included: "Double shot of espresso. Optional using with non sugar, white sugar or brown sugar",
    },
    {
      drinkId: 6,
      cafeName: "Condensed milk Coffee",
      image: require("../shared/drink/milk.jpg"),
      price: "55.000VND",
      description: "Rich and sweet, made by mixing brewed coffee with thick, sweetened condensed milk, often served iced. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.5,
      included: "Double shot of espresso with condensed milk",
    },
    {
      drinkId: 7,
      cafeName: "White Coffee",
      image: require("../shared/drink/white.jpg"),
      price: "60.000VND",
      description: "A light roast coffee, typically with milk or cream added, resulting in a lighter color and smoother taste. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.5,
      included: "Condensed milk, single shot of espresso with white milk",
    },
    {
      drinkId: 8,
      cafeName: "Latte",
      image: require("../shared/drink/latte.jpg"),
      price: "60.000VND",
      description: "Smooth and creamy, consisting of one or two shots of espresso with a larger amount of steamed milk and a small amount of milk foam. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.5,
      included: "White milk, single shot of espresso,optional using with non sugar, white sugar or brown sugar.",
    },
    {
      drinkId: 9,
      cafeName: "Caramel Macchiato",
      image: require("../shared/drink/cara.jpg"),
      price: "65.000VND",
      description: "A sweet and layered drink with vanilla-flavored syrup, steamed milk, a shot of espresso, and a caramel drizzle on top. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.7,
      included: "White milk, single shot of espresso,caramel syrup and Condensed milk.",
    },
    {
      drinkId: 10,
      cafeName: "Mocha",
      image: require("../shared/drink/mocha.jpg"),
      price: "65.000VND",
      description: "A chocolate-flavored coffee drink made with espresso, steamed milk, and chocolate syrup or powder, often topped with whipped cream. Be able to : Ice or Hot.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.5,
      included: "White milk, single shot of espresso,chocolate powder and Condensed milk.",
    },
    {
      drinkId: 11,
      cafeName: "Coldbrew",
      image: require("../shared/drink/coldbrew.jpg"),
      price: "60.000VND",
      description: "Refreshing and smooth, made by steeping coarse coffee grounds in cold water for an extended period, typically served over ice. Iced only.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.9,
      included: "With yellow-orange. Serving in bottle 100ml.",
    },
    {
      drinkId: 12,
      cafeName: "Americano",
      image: require("../shared/drink/americano.jpg"),
      price: "50.000VND",
      description: "A smooth and strong coffee made by diluting a shot or two of espresso with hot water, resulting in a rich flavor similar to traditional drip coffee but with a slightly lighter taste. Be able to: Hot or Ice.",
      categoryId: 2,
      coffeeId: 2,
      rating: 4.3,
      included: "Optional using with non sugar, white sugar or brown sugar",
    },
    {
      drinkId: 13,
      cafeName: "Hot Tea Pot",
      image: require("../shared/drink/hotpottea.jpg"),
      price: "85.000VND",
      description: "A classic serving of hot tea brewed in a teapot, offering a comforting and aromatic experience with a choice of various tea leaves, such as green and herbal.",
      categoryId: 2,
      coffeeId: 3,
      rating: 4.5,
      included: "Optional using with non sugar, white sugar or brown sugar",
    },
    {
      drinkId: 14,
      cafeName: "Tropical Tea",
      image: require("../shared/drink/tropicaltea.jpg"),
      price: "60.000VND",
      description: "A refreshing blend of tea infused with tropical fruits like mango, pineapple, and passion fruit, offering a vibrant and fruity flavor. Iced only.",
      categoryId: 2,
      coffeeId: 3,
      rating: 4.8,
      included: "Topping : Lychee jelly. Optional using with non sugar, white sugar or brown sugar.",
    },
    {
      drinkId: 15,
      cafeName: "Green apple with Acerola cherry Tea",
      image: require("../shared/drink/greenappletea.jpg"),
      price: "60.000VND",
      description: "A fruity and tangy tea blend featuring the flavors of crisp apples and sweet cherries, creating a balanced and delightful drink. Iced only.",
      categoryId: 2,
      coffeeId: 3,
      rating: 4.6,
      included: "Topping : Aloe vera. Optional using with non sugar, white sugar or brown sugar.",
    },
    {
      drinkId: 16,
      cafeName: "Watermelon Lychee Tea",
      image: require("../shared/drink/watermelontea.jpg"),
      price: "60.000VND",
      description: "A refreshing and unique combination of tea infused with the juicy sweetness of watermelon and the subtle floral notes of lychee. Iced only.",
      categoryId: 2,
      coffeeId: 3,
      rating: 4.8,
      included: "Topping : Aloe vera. Optional using with non sugar, white sugar or brown sugar.",
    },
    {
      drinkId: 17,
      cafeName: "Lychee Tea",
      image: require("../shared/drink/lycheetea.jpg"),
      price: "60.000VND",
      description: "A fragrant and sweet tea made with the delicate flavor of lychee fruit, providing a light and floral taste. Iced only.",
      categoryId: 2,
      coffeeId: 3,
      rating: 4.7,
      included: "Topping : Lychee. Optional using with non sugar, white sugar or brown sugar.",
    },
    {
      drinkId: 18,
      cafeName: "The Berry",
      image: require("../shared/drink/berry.jpg"),
      price: "75.000VND",
      description: "A refreshing and tangy fermented tea blend featuring a mix of berries and strawberries, offering a burst of fruity flavors with a slightly tart finish. Iced only.",
      categoryId: 2,
      coffeeId: 4,
      rating: 4.7,
      included: "Serving in bottle 230ml. Kombucha mix between mulberry and strawberry.",
    },
    {
      drinkId: 19,
      cafeName: "The Pink",
      image: require("../shared/drink/pink.jpg"),
      price: "75.000VND",
      description: "A tropical and invigorating kombucha blend combining the sweet and exotic taste of guava with the familiar sweetness of strawberries, resulting in a vibrant and refreshing drink. Iced only.",
      categoryId: 2,
      coffeeId: 4,
      rating: 4.5,
      included: "Serving in bottle 230ml. Kombucha mix between guava and strawberry.",
    },
    {
      drinkId: 20,
      cafeName: "The Yellow",
      image: require("../shared/drink/yellow.jpg"),
      price: "75.000VND",
      description: "A lively and zesty kombucha made with the distinctively tart and aromatic flavor of passionfruit, delivering a refreshing and invigorating experience. Iced only.",
      categoryId: 2,
      coffeeId: 4,
      rating: 4.1,
      included: "Serving in bottle 230ml. Kombucha passionfruit.",
    },
    {
      drinkId: 21,
      cafeName: "Thai red Milktea",
      image: require("../shared/drink/redmilktea.jpg"),
      price: "60.000VND",
      description: "A rich and creamy tea made with strongly brewed black tea, sweetened condensed milk, and spices, known for its vibrant orange-red color and sweet, aromatic flavor. Iced only.",
      categoryId: 2,
      coffeeId: 5,
      rating: 4.7,
      included: "Topping: Grass jelly with White tapioca pearl.",
    },
    {
      drinkId: 22,
      cafeName: "Thai green Milktea",
      image: require("../shared/drink/greenmilktea.jpg"),
      price: "60.000VND",
      description: "A refreshing and sweet drink made from brewed green tea, sweetened condensed milk, and sometimes a hint of jasmine, resulting in a light green color and smooth, floral taste. Iced only.",
      categoryId: 2,
      coffeeId: 5,
      rating: 4.5,
      included: "Topping: Grass jelly with White tapioca pearl.",
    },
    {
      drinkId: 23,
      cafeName: "Lotus Milktea",
      image: require("../shared/drink/lotusmilktea.jpg"),
      price: "60.000VND",
      description: "A fragrant and delicate milk tea infused with the subtle floral notes of lotus flowers, combined with sweetened milk for a light and soothing beverage. Iced only.",
      categoryId: 2,
      coffeeId: 5,
      rating: 4.1,
      included: "Topping: Grass jelly with White tapioca pearl.",
    },
    {
      drinkId: 24,
      cafeName: "Immunity Booster",
      image: require("../shared/drink/cherryguava.jpg"),
      price: "65.000VND",
      description: "A powerful antioxidant-rich juice blend featuring the tart and vitamin-packed acerola cherries mixed with the sweet and smooth taste of guava, creating a delicious and nutritious beverage. Iced only.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.7,
      included: "Using non sugar, optional : White sugar.",
    },
    {
      drinkId: 25,
      cafeName: "Weightloss",
      image: require("../shared/drink/passionfruitguava.jpg"),
      price: "65.000VND",
      description: "A tropical and tangy blend combining the aromatic tartness of passionfruit with the sweet and exotic flavor of guava, resulting in a refreshing and vibrant drink. Iced only.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.5,
      included: "Using non sugar, optional : White sugar.",
    },
    {
      drinkId: 26,
      cafeName: "Glowing Skin",
      image: require("../shared/drink/beetrootjuice.jpg"),
      price: "65.000VND",
      description: "A unique and invigorating juice combining the earthy sweetness of beetroot, the juicy freshness of watermelon, and the crisp tartness of green apple, offering a flavorful and health-boosting drink. Iced only.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.1,
      included: "Using non sugar, optional : White sugar.",
    },
    {
      drinkId: 27,
      cafeName: "Matcha Latte",
      image: require("../shared/drink/matcha.jpg"),
      price: "60.000VND",
      description: "A creamy and vibrant drink made with finely ground matcha green tea powder, steamed milk, and a touch of sweetness, offering a smooth and earthy flavor with a rich green color. Be able to: Hot or Ice.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.7,
      included: "Topping: Cold milk-foam.",
    },
    {
      drinkId: 28,
      cafeName: "Chocolate Latte",
      image: require("../shared/drink/chocolate.jpg"),
      price: "60.000VND",
      description: "A rich and indulgent beverage combining espresso with steamed milk and chocolate syrup or cocoa powder, topped with a layer of milk foam, creating a warm and chocolaty treat. Be able to: Hot or Ice.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.5,
      included: "Topping: Cold milk-foam.",
    },
    {
      drinkId: 29,
      cafeName: "Beetroot Latte",
      image: require("../shared/drink/betroot.jpg"),
      price: "60.000VND",
      description: "A unique and colorful drink made with finely powdered beetroot, steamed milk, and a hint of sweetener, providing an earthy and slightly sweet flavor with a striking pink hue. Be able to: Hot or Ice.",
      categoryId: 2,
      coffeeId: 6,
      rating: 4.1,
      included: "Topping: Cold milk-foam.",
    },
  ];
  
  export default drinkdetails;
  